# Generated by Django 4.1.1 on 2022-09-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('DataNasc', models.DateField()),
                ('Tel', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('Notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipoTrat', models.CharField(choices=[('Q', 'TENS'), ('M', 'Massagem'), ('A', 'Acupunctura'), ('Q', 'Quinésio'), ('P', 'Pistola'), ('O', 'Outros')], default='Massagem', max_length=1)),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('Descricao', models.TextField(blank=True, null=True)),
                ('Ficheiro', models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/lmfigueiredo/Projectos/CBrasM/Exames'), verbose_name='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
