# Generated by Django 4.1.1 on 2022-10-03 09:59

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='DataNasc',
            field=models.DateField(help_text='Data de nascimento no formato aaaa-mm-ss', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tel',
            field=models.CharField(help_text='Número de de telefone ou telemóvel', max_length=12, verbose_name='Nº Telefone'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(help_text='Nome ccompleto', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='Descricao',
            field=models.TextField(blank=True, help_text='Descrição e tipo de exame', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exames',
            name='Ficheiro',
            field=models.FileField(help_text='Escolha o ficheiro com o exame', upload_to=pathlib.PureWindowsPath('C:/Users/lmfigueiredo/Projectos/CBrasM/Exames'), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exames',
            name='data',
            field=models.DateField(help_text='Data em que foi feito o exame', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='Descricao',
            field=models.TextField(blank=True, help_text='Descrição do tratamento (Outros), ou observações sobre tratamentos', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='data',
            field=models.DateField(auto_now_add=True, help_text='Data em que ocorreu o tratamento', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='tipoTrat',
            field=models.CharField(choices=[('Q', 'TENS'), ('M', 'Massagem'), ('A', 'Acupunctura'), ('Q', 'Quinésio'), ('P', 'Pistola'), ('O', 'Outros')], default='Massagem', help_text='Escolha o ttipo de tratamento efectuado', max_length=1, verbose_name='Tipo de Tratamento'),
        ),
    ]
