# Generated by Django 4.1.1 on 2022-10-07 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_exames_options_alter_tratamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exames',
            options={'ordering': ['-dataex']},
        ),
        migrations.AlterModelOptions(
            name='tratamento',
            options={'ordering': ['-datatrat']},
        ),
        migrations.RenameField(
            model_name='exames',
            old_name='data',
            new_name='dataex',
        ),
        migrations.RemoveField(
            model_name='tratamento',
            name='data',
        ),
        migrations.AddField(
            model_name='tratamento',
            name='datatrat',
            field=models.DateField(default=datetime.date.today, help_text='Data em que ocorreu o tratamento', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='tipoTrat',
            field=models.CharField(choices=[('Q', 'TENS'), ('M', 'Massagem'), ('A', 'Acupunctura'), ('Q', 'Quinésio'), ('P', 'Pistola'), ('O', 'Outros')], default='Massagem', help_text='Escolha o tipo de tratamento efectuado', max_length=1, verbose_name='Tipo de Tratamento'),
        ),
    ]
